import express from "express"
import { Webhooks } from "@octokit/webhooks"
import { env } from "./env.js"
import { createInstallationOctokit } from "./github.js"
import { createLogger } from "./log.js"
import { commitAndPushDocsBranch, generateDocsForPr } from "./docs-agent.js"

const log = createLogger(env.logLevel as any)

const PROXY_ENV_KEYS = ["HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy", "NO_PROXY", "no_proxy"] as const

// Apply proxy env (mainly for `git clone/fetch/push` inside Docker)
if (env.useProxy && env.proxyUrl) {
  const p = env.proxyUrl
  process.env.HTTP_PROXY ??= p
  process.env.HTTPS_PROXY ??= p
  process.env.ALL_PROXY ??= p
  process.env.http_proxy ??= p
  process.env.https_proxy ??= p
  process.env.all_proxy ??= p
  if (env.noProxy) {
    process.env.NO_PROXY ??= env.noProxy
    process.env.no_proxy ??= env.noProxy
  }
  log.info("Proxy enabled", { proxyUrl: p, noProxy: env.noProxy })
} else if (!env.useProxy) {
  for (const k of PROXY_ENV_KEYS) delete process.env[k]
  log.info("Proxy disabled by USE_PROXY=false")
}

const EXPERIMENTAL_NOTICE_LINES = [
  "---",
  "Experimental bot notice:",
  "- This output is generated by AstrBot-Doc-Agent for review only.",
  "- It does not represent the final documentation form."
]

type TriggerSource = "pr_merged" | "pr_comment"
type TriggerContext = {
  source: TriggerSource
  manualInstruction?: string
  requestedBy?: string
}

type Job = { key: string; startedAt?: number; run: () => Promise<void> }

const pending = new Map<string, Job>()
const inflight = new Set<string>()
let running = 0

function enqueue(job: Job) {
  if (inflight.has(job.key)) return { ok: true, deduped: true }
  if (pending.has(job.key)) pending.delete(job.key) // move to end (newest wins)
  if (!pending.has(job.key) && pending.size >= env.maxQueueSize) return { ok: false, reason: "queue_full" as const }
  pending.set(job.key, job)
  pump()
  return { ok: true, deduped: false }
}

function pump() {
  while (running < env.maxConcurrentJobs && pending.size > 0) {
    const [key, job] = pending.entries().next().value as [string, Job]
    pending.delete(key)
    inflight.add(key)
    running += 1
    job.startedAt = Date.now()
    void job
      .run()
      .catch((e) => log.error("Job failed", { key, err: String(e?.message ?? e) }))
      .finally(() => {
        running -= 1
        inflight.delete(key)
        pump()
      })
  }
}

function parseRepo(full: string): { owner: string; repo: string } {
  const [owner, repo] = full.split("/", 2)
  if (!owner || !repo) throw new Error(`Invalid repo: ${full}`)
  return { owner, repo }
}

function truncateLines(text: string, maxLines: number) {
  const lines = text.split(/\r?\n/)
  if (lines.length <= maxLines) return text
  return lines.slice(0, maxLines).join("\n") + `\n\n# --- truncated (${lines.length - maxLines} more lines) ---\n`
}

async function getDefaultBranch(octokit: any, owner: string, repo: string) {
  const r = await octokit.repos.get({ owner, repo })
  return r.data.default_branch
}

async function ensureDocsPr(params: {
  octokit: any
  docsOwner: string
  docsRepo: string
  head: string
  base: string
  title: string
  body: string
}) {
  const list = await params.octokit.pulls.list({
    owner: params.docsOwner,
    repo: params.docsRepo,
    state: "open",
    head: `${params.docsOwner}:${params.head}`
  })
  if (list.data.length > 0) return list.data[0].html_url as string

  const pr = await params.octokit.pulls.create({
    owner: params.docsOwner,
    repo: params.docsRepo,
    head: params.head,
    base: params.base,
    title: params.title,
    body: params.body
  })
  return pr.data.html_url as string
}

function withExperimentalNotice(lines: string[]): string {
  return [...lines, "", ...EXPERIMENTAL_NOTICE_LINES].join("\n")
}

function escapeRegExp(input: string) {
  return input.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function parseMentionInstruction(commentBody: string, botMention: string) {
  const re = new RegExp(`@${escapeRegExp(botMention)}\\b`, "i")
  const hit = re.exec(commentBody || "")
  if (!hit) return { shouldTrigger: false as const }

  let tail = (commentBody || "").slice(hit.index + hit[0].length).trim()
  tail = tail.replace(/^[\s:\uFF1A,\uFF0C;\-]+/, "").trim()
  if (!tail) return { shouldTrigger: true as const, manualInstruction: undefined as string | undefined }

  const cmd = /^generate\s+docs\b/i.exec(tail)
  if (!cmd) return { shouldTrigger: true as const, manualInstruction: tail }

  const rest = tail.slice(cmd[0].length).trim()
  return {
    shouldTrigger: true as const,
    manualInstruction: rest.length > 0 ? rest : undefined
  }
}

function enqueuePrJob(repoFull: string, prNumber: number, trigger: TriggerContext) {
  const key = `${repoFull}#${prNumber}`
  const enq = enqueue({
    key,
    run: async () => {
      const start = Date.now()
      log.info("Job start", { key, trigger })
      try {
        const m0 = process.memoryUsage()
        log.info("Job memory (start)", {
          key,
          rss: m0.rss,
          heapUsed: m0.heapUsed,
          heapTotal: m0.heapTotal,
          external: m0.external
        })
        await processPullRequest(repoFull, prNumber, trigger)
        const m1 = process.memoryUsage()
        log.info("Job memory (end)", {
          key,
          rss: m1.rss,
          heapUsed: m1.heapUsed,
          heapTotal: m1.heapTotal,
          external: m1.external
        })
      } finally {
        log.info("Job done", { key, ms: Date.now() - start })
      }
    }
  })

  if (!enq.ok) {
    log.warn("Queue full; dropping event", { key, trigger })
    return
  }
  if (enq.deduped) log.info("Deduped event (already running)", { key, trigger })
  else log.info("Enqueued job", { key, trigger, pending: pending.size, running })
}

const webhooks = new Webhooks({ secret: env.githubWebhookSecret })

webhooks.on("pull_request.closed", handlePullRequestClosed)
webhooks.on("issue_comment.created", handleIssueCommentCreated)

async function handlePullRequestClosed(event: any) {
  const repoFull = event.payload.repository?.full_name as string
  const prNumber = event.payload.pull_request?.number as number
  const merged = Boolean(event.payload.pull_request?.merged)

  if (!repoFull || !prNumber) {
    log.warn("Webhook missing repo/pr", { repoFull, prNumber })
    return
  }

  if (!env.codeRepos.includes(repoFull)) {
    if (repoFull === env.docsRepo) log.info("Ignored docs repo event", { repoFull })
    else log.warn("Ignored repo (not allowlisted)", { repoFull, allow: env.codeRepos })
    return
  }

  if (!merged) {
    log.info("Ignore closed-but-not-merged PR", { repo: repoFull, prNumber })
    return
  }

  log.info("Merged PR event received", { repo: repoFull, prNumber })
  enqueuePrJob(repoFull, prNumber, { source: "pr_merged" })
}

async function handleIssueCommentCreated(event: any) {
  const repoFull = event.payload.repository?.full_name as string
  const issue = event.payload.issue
  const isPullRequestComment = Boolean(issue?.pull_request)
  const prNumber = issue?.number as number | undefined
  const body = String(event.payload.comment?.body ?? "")
  const sender = String(event.payload.sender?.login ?? "")

  if (!repoFull || !prNumber || !isPullRequestComment) return
  if (!env.codeRepos.includes(repoFull)) return

  const parsed = parseMentionInstruction(body, env.botMention)
  if (!parsed.shouldTrigger) return

  log.info("PR comment command received", {
    repo: repoFull,
    prNumber,
    sender,
    hasManualInstruction: Boolean(parsed.manualInstruction)
  })

  enqueuePrJob(repoFull, prNumber, {
    source: "pr_comment",
    manualInstruction: parsed.manualInstruction,
    requestedBy: sender || undefined
  })
}

async function processPullRequest(repoFull: string, prNumber: number, trigger: TriggerContext) {
  const timeoutMs = Math.max(1, env.jobTimeoutSeconds) * 1000

  const { owner: codeOwner, repo: codeName } = parseRepo(repoFull)
  const { owner: docsOwner, repo: docsName } = parseRepo(env.docsRepo)

  const codeInst = await createInstallationOctokit({
    appId: env.githubAppId,
    privateKey: env.githubAppPrivateKey,
    owner: codeOwner,
    repo: codeName
  })

  const docsInst = await createInstallationOctokit({
    appId: env.githubAppId,
    privateKey: env.githubAppPrivateKey,
    owner: docsOwner,
    repo: docsName
  })

  const pr = await codeInst.octokit.pulls.get({
    owner: codeOwner,
    repo: codeName,
    pull_number: prNumber
  })

  if (trigger.source === "pr_merged" && !pr.data.merged) {
    log.info("Skip run: PR is not merged", { repo: repoFull, prNumber })
    return
  }

  const files = await codeInst.octokit.pulls.listFiles({
    owner: codeOwner,
    repo: codeName,
    pull_number: prNumber,
    per_page: 100
  })

  const prFiles = files.data.map((f: any) => f.filename).filter(Boolean)

  const patchResp = await codeInst.octokit.pulls.get({
    owner: codeOwner,
    repo: codeName,
    pull_number: prNumber,
    mediaType: { format: "patch" }
  })

  const patch = truncateLines(String(patchResp.data ?? ""), env.maxPatchLines)

  const baseBranch = await getDefaultBranch(docsInst.octokit, docsOwner, docsName)
  const branch = `docs-agent/${codeOwner}-${codeName}-pr-${prNumber}`

  const runRes = await generateDocsForPr({
    docsRepo: env.docsRepo,
    docsToken: docsInst.token,
    baseBranch,
    branch,
    codeRepo: repoFull,
    prNumber,
    prTitle: pr.data.title ?? "",
    prBody: pr.data.body ?? "",
    prUrl: pr.data.html_url ?? "",
    prFiles,
    prPatch: patch,
    manualInstruction: trigger.manualInstruction,
    triggerSource: trigger.source,
    dataDir: env.dataDir,
    timeoutMs,
    logAgent: env.logAgent || env.logLevel === "debug",
    llm: {
      provider: env.llmProvider,
      apiKey: env.llmApiKey,
      model: env.llmModel,
      baseUrl: env.llmBaseUrl || undefined,
      temperature: env.llmTemperature
    }
  })

  if (!runRes.changed) {
    log.info("No docs changes; comment only", { prNumber })
    const commentBody = withExperimentalNotice([
      "No docs changes were generated in this run (docs repo had no updates).",
      "",
      `Docs repo: ${env.docsRepo}`,
      `Trigger: ${trigger.source === "pr_comment" ? "PR comment command" : "PR merged"}`,
      ...(trigger.requestedBy ? [`Requested by: @${trigger.requestedBy}`] : []),
      ...(trigger.manualInstruction
        ? ["", "Manual instruction:", "```text", trigger.manualInstruction, "```"]
        : []),
      ...(runRes.summary
        ? [
            "",
            "---",
            "AI change summary (not committed):",
            "",
            runRes.summary.length > 3500 ? `${runRes.summary.slice(0, 3500)}\n\n(truncated)` : runRes.summary
          ]
        : [])
    ])

    await codeInst.octokit.issues.createComment({
      owner: codeOwner,
      repo: codeName,
      issue_number: prNumber,
      body: commentBody
    })
    return
  }

  await commitAndPushDocsBranch({
    docsRepo: env.docsRepo,
    docsToken: docsInst.token,
    checkoutDir: runRes.checkoutDir,
    branch,
    baseBranch,
    commitMessage: `docs: update for ${repoFull}#${prNumber}`,
    timeoutMs,
    octokit: docsInst.octokit
  })

  const docsPrUrl = await ensureDocsPr({
    octokit: docsInst.octokit,
    docsOwner,
    docsRepo: docsName,
    head: branch,
    base: baseBranch,
    title: runRes.docsPrTitle ? String(runRes.docsPrTitle) : `Docs: ${repoFull}#${prNumber}`,
    body: withExperimentalNotice([
      "Generated automatically by astrbot-docs-agent-server.",
      "",
      `- Upstream PR: https://github.com/${repoFull}/pull/${prNumber}`,
      `- Trigger: ${trigger.source === "pr_comment" ? "PR comment command" : "PR merged"}`,
      ...(trigger.requestedBy ? [`- Requested by: @${trigger.requestedBy}`] : []),
      ...(trigger.manualInstruction ? [`- Manual instruction provided: yes`] : []),
      ...(trigger.manualInstruction ? ["", "Manual instruction:", "```text", trigger.manualInstruction, "```"] : []),
      ...(runRes.summary
        ? [
            "",
            "---",
            "AI change summary:",
            "",
            runRes.summary.length > 5000 ? `${runRes.summary.slice(0, 5000)}\n\n(truncated)` : runRes.summary
          ]
        : []),
      "",
      "Please review manually before merging."
    ])
  })

  await codeInst.octokit.issues.createComment({
    owner: codeOwner,
    repo: codeName,
    issue_number: prNumber,
    body: withExperimentalNotice([
      "Generated docs update PR (pending manual review):",
      docsPrUrl,
      `Trigger: ${trigger.source === "pr_comment" ? "PR comment command" : "PR merged"}`,
      ...(trigger.requestedBy ? [`Requested by: @${trigger.requestedBy}`] : []),
      ...(runRes.summary
        ? [
            "",
            "---",
            "AI change summary:",
            "",
            runRes.summary.length > 3500 ? `${runRes.summary.slice(0, 3500)}\n\n(truncated)` : runRes.summary
          ]
        : [])
    ])
  })

  log.info("Done", { prNumber, docsPrUrl })
}

const app = express()

app.get("/healthz", (_req, res) => res.status(200).send("ok"))
app.get("/queue", (_req, res) => {
  res.json({
    running,
    inflight: [...inflight.values()],
    pending: [...pending.keys()],
    maxConcurrentJobs: env.maxConcurrentJobs,
    maxQueueSize: env.maxQueueSize
  })
})

// Keep raw body for signature verification
app.post(
  "/webhooks/github",
  express.raw({ type: "*/*", limit: env.webhookBodyLimit }),
  async (req, res) => {
    try {
      const id = req.header("x-github-delivery") ?? ""
      const name = req.header("x-github-event") ?? ""
      const signature = req.header("x-hub-signature-256") ?? ""

      await webhooks.verifyAndReceive({
        id,
        name,
        signature,
        payload: (req.body as Buffer).toString("utf-8")
      })

      res.status(202).send("accepted")
    } catch (e: any) {
      log.warn("Webhook rejected", { err: String(e?.message ?? e) })
      res.status(400).send("bad request")
    }
  }
)


app.use((err: any, _req: any, res: any, next: any) => {
  if (err?.type === "entity.too.large" || err?.name === "PayloadTooLargeError") {
    log.warn("Webhook payload too large", { limit: env.webhookBodyLimit })
    res.status(413).send("payload too large")
    return
  }
  next(err)
})

app.listen(env.port, "0.0.0.0", () => {
  log.info(`Listening on :${env.port}`)
  log.info("Allowlisted code repos", {
    codeRepos: env.codeRepos,
    docsRepo: env.docsRepo,
    botMention: env.botMention,
    useProxy: env.useProxy,
    webhookBodyLimit: env.webhookBodyLimit
  })
})

